#
# Module manifest for module 'PSGet_PowerShellGet'
#
# Generated by: Microsoft Corporation
#
# Generated on: 31.03.2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSModule.psm1'

# Version number of this module.
ModuleVersion = '1.1.3.2'

# ID used to uniquely identify this module
GUID = '1d73a601-4a6c-43c5-ba3f-619b18bbb404'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = '(c) Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell module with commands for discovering, installing, updating and publishing the PowerShell artifacts like Modules, DSC Resources, Role Capabilities and Scripts.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'PackageManagement'; ModuleVersion = '1.0.0.1'; })

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'PSGet.Format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = 'Install-Module', 'Find-Module', 'Save-Module', 'Update-Module', 
               'Publish-Module', 'Get-InstalledModule', 'Uninstall-Module', 
               'Find-Command', 'Find-DscResource', 'Find-RoleCapability', 
               'Install-Script', 'Find-Script', 'Save-Script', 'Update-Script', 
               'Publish-Script', 'Get-InstalledScript', 'Uninstall-Script', 
               'Test-ScriptFileInfo', 'New-ScriptFileInfo', 'Update-ScriptFileInfo', 
               'Get-PSRepository', 'Set-PSRepository', 'Register-PSRepository', 
               'Unregister-PSRepository', 'Update-ModuleManifest'

# Cmdlets to export from this module
# CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = 'inmo', 'fimo', 'upmo', 'pumo'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'PSModule.psm1', 'PSGet.Format.ps1xml', 'PSGet.Resource.psd1'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    #SupportedPowerShellGetFormatVersions of this module
    SupportedPowerShellGetFormatVersions = '1.x'

    #PackageManagementProviders of this module
    PackageManagementProviders = 'PSModule.psm1'

    #VersionControl of this module
    VersionControl = '{"Hash":"E8D78A98212065FD4FE9C857A358EAEE0F25BD5C9DC204EE5145BF4445518780","HashAlgorithm":"SHA256","Version":"1.1.3.2"}'

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Packagemanagement','Provider','PSEdition_Desktop','PSEdition_Core','Linux','Mac'

        # A URL to the license for this module.
        LicenseUri = 'https://go.microsoft.com/fwlink/?LinkId=829061'

        # A URL to the main website for this project.
        ProjectUri = 'https://go.microsoft.com/fwlink/?LinkId=828955'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '- PowerShellCore support
- Security enhancements including the enforcement of catalog-signed modules during installation
- Authenticated Repository support
- Proxy Authentication support
- Responses to a number of user requests and issues'

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
} # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'http://go.microsoft.com/fwlink/?LinkId=393271'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

